---

- hosts: localhost
  connection: local

  tasks:
    - name: deploy_stack_compose
      docker_stack:
        state: present
        name: w
        compose:
          - ./docker-compose/docker-compose.yml